export const START_LOGIN = 'START_LOGIN';
export const FINISH_LOGIN = 'FINISH_LOGIN';
export const LOGOUT = 'LOGOUT';
export const HANDLE_LOGIN_ERROR = 'HANDLE_LOGIN_ERROR';
export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const MERGE_USERS = 'MERGE_USERS';
export const REMOVE_USER = 'REMOVE_USER';

export const MERGE_KITS = 'MERGE_KITS';
export const REMOVE_KIT = 'REMOVE_KIT';

export const MERGE_ORGANIZATIONS = 'MERGE_ORGANIZATIONS';

export const START_SEARCH = 'START_SEARCH';
export const RETURN_SEARCH_RESULTS = 'RETURN_SEARCH_RESULTS';

export const OPEN_OVERLAY = 'OPEN_OVERLAY';
export const CLOSE_OVERLAY = 'CLOSE_OVERLAY';

export const ADMIN_UPDATE_USER_ROLE = 'ADMIN_UPDATE_USER_ROLE';
